Define ci.modifiers in open-source shim
Summary:
Buck2's bootstrap build is failing since {D113293082}.

```lang=log,counterexample
BUILD FAILED
Error evaluating build file: `gh_facebook_buck2//:BUCK`

Caused by:
    error: Object of type `struct` has no attribute `modifiers`
      --> BUCK:13:9
       |
    13 |           ci.modifiers(
       |  _________^
    14 | |             [
    15 | |                 "ovr_config//cpu:arm64",
    16 | |                 "ovr_config//build_mode/constraints:dev",
    17 | |             ],
    18 | |             ci.skip_test(),
    19 | |         ),
       | |_________^
       |
```

Reviewed By: cjlongoria

Differential Revision: D114409707

fbshipit-source-id: 7a079360f302938dd47fd40f5a36377f97e77393